# Practical 08
## Aim: 
    Perform SVD analysis of a network.

In [1]:
library(igraph)


Attaching package: ‘igraph’


The following objects are masked from ‘package:stats’:

    decompose, spectrum


The following object is masked from ‘package:base’:

    union




In [2]:
a <- matrix(c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1), 9, 4)

In [3]:
print(a)

      [,1] [,2] [,3] [,4]
 [1,]    1    1    0    0
 [2,]    1    1    0    0
 [3,]    1    1    0    0
 [4,]    1    0    1    0
 [5,]    1    0    1    0
 [6,]    1    0    1    0
 [7,]    1    0    0    1
 [8,]    1    0    0    1
 [9,]    1    0    0    1


In [4]:
svd(a)

$d
[1] 3.464102e+00 1.732051e+00 1.732051e+00 1.359740e-16

$u
            [,1]       [,2]          [,3]          [,4]
 [1,] -0.3333333  0.4714045 -3.202997e-16  3.693981e-01
 [2,] -0.3333333  0.4714045 -3.415341e-16  4.459029e-01
 [3,] -0.3333333  0.4714045  8.520300e-18 -8.153010e-01
 [4,] -0.3333333 -0.2357023 -4.082483e-01  7.849070e-17
 [5,] -0.3333333 -0.2357023 -4.082483e-01  1.340019e-16
 [6,] -0.3333333 -0.2357023 -4.082483e-01  1.340019e-16
 [7,] -0.3333333 -0.2357023  4.082483e-01  1.182076e-16
 [8,] -0.3333333 -0.2357023  4.082483e-01  1.182076e-16
 [9,] -0.3333333 -0.2357023  4.082483e-01  1.182076e-16

$v
           [,1]       [,2]          [,3] [,4]
[1,] -0.8660254  0.0000000 -4.378026e-17  0.5
[2,] -0.2886751  0.8164966 -2.509507e-16 -0.5
[3,] -0.2886751 -0.4082483 -7.071068e-01 -0.5
[4,] -0.2886751 -0.4082483  7.071068e-01 -0.5